services:
  peer1:
    container_name: peer1
    image: p2p
    environment:
      - DISPLAY=:0
      - APPNAME=peer1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - cse471

  peer2:
    container_name: peer2
    image: p2p
    environment:
      - DISPLAY=:0
      - APPNAME=peer2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - cse471

  peer3:
    container_name: peer3
    image: p2p
    environment:
      - DISPLAY=:0
      - APPNAME=peer3
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - cse471

networks:
  cse471:
    name: cse471
